### ISSUE TITLE
せっかくすごい経験なので要約の内容を変更してみるとより良いかも

### ISSUE THREAD

**Issue by mijinco0612** [miyakona/Curriculm-Vitae#2]
経歴要約
大学卒業後、株式会社DMM.com Labo（合同会社DMM.com）に入社。
主な配属は電子書籍事業部です。

主な業務内容は保守運営で、サービスの改修やサーバの設定変更などに関わりました。
その他、社内の新規サービス立ち上げの際のヘルプにも関わりました。

> 主な業務内容は保守運営で、サービスの改修やサーバの設定変更などに関わりました。

と書くよりも、

```
新規開発サービスの立ち上げやチームビルド、実装、リリース、運用まで、複数回関わってきました。
また、キャリアを通して運用に携わり続けたサービスは関わった五年間で
年間売り上げがxxx円(2014年度)からxxx円(2019年度)まで急成長しており、
プロダクトが拡大するなからサービスを維持し続けられるようにxxxやxxxに
注意しながら業務に携わってきました。
```

みたいな感じで触れられるといいかなと思いました。（運用保守だったんだーふーんって流される可能性あるかも）
選考官はサマリをみて、おっ！と思わないかぎりは詳細をまでは深く読まない傾向にある
（大抵の場合、書類選考１件に費やす時間は一分程度で一旦見切りをつけたりするらしいです。）
ので、プロダクト規模やその成長に関わってきたこと、サービス維持に貢献しつつ、新規プロジェクトを歴任してきたことに触れる（これは事実だとおもうので）と魅力が伝わりやすいかなと思いました。

**Comment by miyakona** [comment]
@mijinco0612 
ありがとうございます！具体的にアドバイスいただけたので、修正しやすいです。
ご指摘いただいたとおりに、修正してみます。

**Comment by miyakona** [comment]
こちらで修正しましたので、よければ御覧ください。
https://github.com/miyakona/Curriculm-Vitae/commit/5c48187236f0b375e9bb4fb79d496c083adbf320

**Comment by mijinco0612** [comment]
拝見しました！いいと思います！

**Comment by mijinco0612** [comment]
では、この件は完了ってことでクローズしときますね！
